engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.py"
exclude_paths:
- datalists/
